from errno import EALREADY, EINPROGRESS, EWOULDBLOCK, ECONNRESET, EINVAL, \
	ENOTCONN, ESHUTDOWN, EINTR, EISCONN, EBADF, ECONNABORTED, EPIPE, EAGAIN, errorcode

_DISCONNECTED = frozenset((ECONNRESET, ENOTCONN, ESHUTDOWN, ECONNABORTED, EPIPE, EBADF))

_SHOULDCONTINUE = frozenset((EWOULDBLOCK, EAGAIN))

_CONNECTING = frozenset((EWOULDBLOCK, EALREADY, EINPROGRESS))
